### ISSUE TITLE
Add effective number of parameters?

### ISSUE THREAD

**Issue by LeeviLindgren** [sor16/R2D2_shiny#1]
[Aguilar and Bürkner (2022)](https://arxiv.org/pdf/2208.07132.pdf) derive the shrinkage factor $\kappa_i$  for each parameter $\beta_i$ in the R2D2 prior. One can then compute the effective number of parameters as $$p_{eff} = \sum_{i=1}^p  (1-\kappa_i). $$ If each predictor is standardized to have zero mean and unit variance, the expression for the shrinkage factor is
$$\kappa_i = \frac{1}{1 + \phi_i \omega \sum x_i^2 }$$ 
It would be nice to have also visualization of the distribution of $p_{eff} / p$.

**Comment by sor16** [comment]
Thank you for creating the issue Leevi. Visualizing $p_{eff}/p$ is very good idea. I will take a look at this and be in touch.
